In [1]:
import torch

/home/liang/miniconda3/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [15]:
# 生成一个维度为3的张量，三个维度的维数分别为1,2,3的张量tensor_1
tensor_1 = torch.randn((1,2,3))

# 输出张量tensor_1的维度和维数信息
print("张量tensor_1为\n", tensor_1)
print("\n张量的形状为：", tensor_1.size())
print("张量第0个维度的维数为：", tensor_1.size(0))
print("张量第1个维度的维数为：", tensor_1.size(1))
print("张量第2个维度的维数为：", tensor_1.size(2))

张量tensor_1为
 tensor([[[-0.1632,  1.1833, -0.6498],
         [-0.9807, -0.1747, -1.2085]]])

张量的形状为： torch.Size([1, 2, 3])
张量第0个维度的维数为： 1
张量第1个维度的维数为： 2
张量第2个维度的维数为： 3


In [7]:
# 张量的形状
tensor_1 = torch.tensor([1, 2, 3, 4, 5])
print("张量tensor_1为：", tensor_1)
print("张量tensor_1的形状为：", tensor_1.size())
print("张量tensor_1的形状为：", tensor_1.shape)

张量tensor_1为： tensor([1, 2, 3, 4, 5])
张量tensor_1的形状为： torch.Size([5])
张量tensor_1的形状为： torch.Size([5])


In [12]:
# 张量的数学运算
tensor_1 = torch.ones(3, 4)
tensor_2 = torch.randn(3, 4)

print(tensor_1)
print(tensor_2)
print("\nsub方法进行张量减法运算结果\n", tensor_1.sub(tensor_2))
print("\nsubtract方法进行张量减法运算结果\n", tensor_1.subtract(tensor_2))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[-0.1934,  0.9732, -0.5484,  0.5571],
        [ 0.3391, -0.1515,  0.2035,  1.1863],
        [ 0.1748,  0.9750,  1.0552, -0.1245]])

sub方法进行张量减法运算结果
 tensor([[ 1.1934,  0.0268,  1.5484,  0.4429],
        [ 0.6609,  1.1515,  0.7965, -0.1863],
        [ 0.8252,  0.0250, -0.0552,  1.1245]])

subtract方法进行张量减法运算结果
 tensor([[ 1.1934,  0.0268,  1.5484,  0.4429],
        [ 0.6609,  1.1515,  0.7965, -0.1863],
        [ 0.8252,  0.0250, -0.0552,  1.1245]])


In [51]:
tensor_1 = torch.randn(3, 5)
print("张量tensor_1为：\n", tensor_1)

# 取得张量tensor_1第一列
tensor_col1 = tensor_1[:,0]
print("\n获取张量tensor1的第一列为：\n", tensor_col1)

# 取得张量tensor_1第一行
tensor_row1 = tensor_1[0,:]
print("\n获取张量tensor1的第一列为：\n", tensor_row1)

# 取得张量tensor_1倒数两列
tensor_cols = tensor_1[:,-2:]
print("\n获取张量tensor1的倒数两列为：\n", tensor_cols)

# 取得张量tensor_1倒数两行
tensor_rows = tensor_1[-2:,:]
print("\n获取张量tensor1的倒数两行为：\n", tensor_rows)

张量tensor_1为：
 tensor([[-1.9195,  0.9342,  1.0556,  1.5316, -1.2903],
        [ 0.4775, -0.9406, -1.6118,  1.7087,  0.2679],
        [ 0.8143,  0.3728, -0.1815, -0.1153, -1.0475]])

获取张量tensor1的第一列为：
 tensor([-1.9195,  0.4775,  0.8143])

获取张量tensor1的第一列为：
 tensor([-1.9195,  0.9342,  1.0556,  1.5316, -1.2903])

获取张量tensor1的倒数两列为：
 tensor([[ 1.5316, -1.2903],
        [ 1.7087,  0.2679],
        [-0.1153, -1.0475]])

获取张量tensor1的倒数两行为：
 tensor([[ 0.4775, -0.9406, -1.6118,  1.7087,  0.2679],
        [ 0.8143,  0.3728, -0.1815, -0.1153, -1.0475]])
