# 图片的基本操作

## 图像数据的读取与保存

- `cv2.IMREAD_COLOR`：彩色图像
- `cv2.IMREAD_GRAYSCALE`：灰度图像

In [1]:
import cv2  # opencv读取的格式是BGR
import matplotlib.pyplot as plt
import numpy as np

# %matplotlib inline

In [2]:
img = cv2.imread('cat_dog.jpg')

print("读取图片的数据格式为：", type(img))
print("读取图片的形状为：", img.shape)
print(img)


读取图片的数据格式为： <class 'numpy.ndarray'>
读取图片的形状为： (350, 490, 3)
[[[ 80 131  93]
  [ 81 132  94]
  [ 84 135  97]
  ...
  [ 31  45  21]
  [ 28  42  18]
  [ 28  42  18]]

 [[ 81 132  94]
  [ 82 133  95]
  [ 83 134  96]
  ...
  [ 31  45  21]
  [ 28  42  18]
  [ 28  42  18]]

 [[ 82 133  95]
  [ 82 133  95]
  [ 82 133  95]
  ...
  [ 31  45  21]
  [ 28  42  18]
  [ 28  42  18]]

 ...

 [[ 79 123 100]
  [ 80 124 101]
  [ 81 125 102]
  ...
  [ 59 103  66]
  [ 59 103  66]
  [ 59 103  66]]

 [[ 78 122  99]
  [ 79 123 100]
  [ 81 125 102]
  ...
  [ 59 103  66]
  [ 56 100  63]
  [ 56 100  63]]

 [[ 79 123 100]
  [ 80 124 101]
  [ 82 126 103]
  ...
  [ 59 103  66]
  [ 55  99  62]
  [ 55  99  62]]]


In [3]:
# 图像的现实，也可以创建多个窗口
# cv2.imshow('image', img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

为了便于以后更方便进行图片现实，下面定义一个图片显示函数`cv_show()`

In [4]:
def cv_show(name, img):
    """作用：显示图片

    Args:
        name (字符串): 图片框名称
        img (ndarray): 图片矩阵数据
    """
    cv2.imshow(name, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [3]:
# 读取图片的灰度图
img_gray = cv2.imread('cat_dog.jpg', cv2.IMREAD_GRAYSCALE)
print("读取图片数据的形状为：", img_gray.shape)

# 现实图片
# cv_show('gray image', img_gray)

读取图片数据的形状为： (350, 490)


对于图片的保存，可以使用`cv2.imwrite()`方法实现

In [6]:
cv2.imwrite('cat_dog_gray.jpg', img_gray)

True

## 截取部分图片数据

In [7]:
img_part = cv2.imread('cat_dog.jpg')[0:200, 0:100]
cv_show('part', img_part)

## 颜色通道提取与合并

- `cv2.split()`：图片颜色通道的提取
- `cv2.merge()`：图片颜色通道的合并

In [10]:
# 注意bgr的顺序
# 使用cv2.split()方法分别提取图片的三个通道的数据
b, g, r = cv2.split(img)

# 使用cv2.merge()方法合并图片通道
img_merge = cv2.merge((b, g, r))

如果我们只想保留图片中B、G、R中的一个可以通过下面的方法实现

In [ ]:
# 只保留图片的红色通道
R_img = img.copy()
R_img[:, :, 0] = 0
R_img[:, :, 1] = 0
# 查看处理结果
# cv_show('R', R_img)

# 只保留图片的绿色通道
B_img = img.copy()
B_img[:, :, 0] = 0
B_img[:, :, 2] = 0
# 查看处理结果
# cv_show('B', B_img)

# 只保留图片的蓝色通道
B_img = img.copy()
B_img[:, :, 1] = 0
B_img[:, :, 2] = 0
# 查看处理结果
# cv_show('B', B_img)

## 图片的边界填充